# Project
version=10.0.1
group=com.mrbysco.armorposer

# Common
minecraft_version=1.21.6
neoform_version=1.21.6-20250617.151856
mixin_version=0.15.0+mixin.0.8.7
mixinextras_version=0.4.1

# NeoForge
neo_version=21.6.20-beta
parchment_minecraft_version=1.21.5
parchment_mapping_version=2025.06.15

# Fabric
fabric_version=0.128.1+1.21.6
fabric_loader_version=0.16.14
cloth_config_version=19.0.147
mod_menu_version=15.0.0-beta.3

# Mod options
mod_name=ArmorPoser
mod_author=Mrbysco
mod_id=armorposer

#Publishing
curseforge_id=450663
modrinth_id=PFwYNrHb

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false